apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3atb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3atb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3atb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3atb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3atb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-safj-tenant/rhtap-demo-app/hacbs-test-project-3atb@sha256:a47664d7f37a9384ba8ef7eea9515389d9975ce2d139ba87a5f10305ad10d37e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
